### PR TITLE
Add workflow for deploying main to GitHub Pages

### PR DESCRIPTION
**Pull request by taesungh**
Create GitHub Actions workflow to deploy main branch to GitHub Pages.
- Address some lingering eslint issues which needed to be resolve for build.
- Update react-scripts and sass

### CODE REVIEW

**Review by ryqndev — COMMENTED** [review]
don't know too much about setting up workflows so i'm going to approve. if anything breaks ill lyk

**Comment by taesungh** [comment]
Tested workflow run in a personal branch, you could do the same if you want to. One important note: before merge, we'll need to change the Pages source in the repository settings to be GitHub Actions.

**Review by ryqndev — APPROVED** [review]

**Comment by ryqndev** [comment]
ok feel free to bundle your change with the settings change. Still expecting one or two pr's to come in today from interns so if you expect the current workflow to break, we can hold off on it. otheriwse go ahead and post on slack when u start doing the change.

**Comment by taesungh** [comment]
Workflow succeeded: [Deploy main to GitHub Pages #1](https://github.com/designatuci/DUCI-website/actions/runs/3925904993)

**Pull request merged**
