### PR TITLE
Update Project Teams page with Fall 2023 info

### LINKED ISSUE #47: Update Project Teams page with Fall 2023 information and form
Our Project Teams coordinators provided updated information about this quarter back throughout the last few weeks. The page should be updated for Fall 2023 with the new Google Form and application deadline.

### PR DESCRIPTION
**Pull request by taesungh**
- Update registration form link and deadline for Fall 2023
- Update description of Project Team and include meeting times
- Hide Join Us link while applications are open

Closes #47.

### CODE REVIEW

**Review by ryqndev — APPROVED** [review]
can you attach a screenshot of the updated look in the pr description.

Other than that, passes the eye test so approving to unblock

**Comment by taesungh** [comment]
Updated look:
Preview of new Project Teams page

**Comment by ryqndev** [comment]
Tiny nit: maybe would like a line break in that middle block of text in pt description - or maybe we would want a higher line height value in general but other than that lgtm

**Comment by taesungh** [comment]
I think our reduced line height is more of a global issue, will look into increasing for content on all pages.

**Pull request merged**
